# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_first_name', models.CharField(max_length=300)),
                ('doctor_last_name', models.CharField(max_length=300)),
                ('hospital', models.CharField(max_length=300)),
                ('created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('date_visit', models.DateField(verbose_name='date visit')),
                ('doctor_note', models.TextField()),
                ('edit_note', models.TextField(default='new note')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=500)),
                ('medication_name', models.CharField(max_length=500)),
                ('medication_type', models.CharField(choices=[('surgery', 'surgery'), ('prescription', 'prescription'), ('other', 'other')], max_length=500)),
                ('description', models.TextField()),
                ('entry', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='register.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Visit'),
        ),
    ]
